<?php
/**
 * Uninstall handler. Removes all plugin data when the plugin is deleted.
 * from the Plugins screen (not on plain deactivation).
 *
 * Removes the interpost_embeddings table and plugin options. Embeddings are
 * derived data and can be regenerated by re-indexing after a reinstall,
 * so full cleanup is safe here.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

function interpost_uninstall_site() {
	global $wpdb;

	delete_option( 'interpost_gemini_api_key' );
	delete_option( 'interpost_db_version' );

	$table = esc_sql( $wpdb->prefix . 'interpost_embeddings' );
	$wpdb->query( "DROP TABLE IF EXISTS `{$table}`" ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.SchemaChange
}

if ( is_multisite() ) {
	$interpost_site_ids = get_sites( array( 'fields' => 'ids' ) );
	foreach ( $interpost_site_ids as $interpost_site_id ) {
		switch_to_blog( $interpost_site_id );
		interpost_uninstall_site();
		restore_current_blog();
	}
} else {
	interpost_uninstall_site();
}
