<?php
/**
 * Uninstall handler — removes all plugin data when the plugin is deleted
 * from the Plugins screen (not on plain deactivation).
 *
 * Removes the pagelace_embeddings table and plugin options. Embeddings are
 * derived data and can be regenerated by re-indexing after a reinstall,
 * so full cleanup is safe here.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

function pagelace_uninstall_site() {
	global $wpdb;

	delete_option( 'pagelace_gemini_api_key' );
	delete_option( 'pagelace_db_version' );

	$table = esc_sql( $wpdb->prefix . 'pagelace_embeddings' );
	$wpdb->query( "DROP TABLE IF EXISTS `{$table}`" ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.SchemaChange
}

if ( is_multisite() ) {
	$pagelace_site_ids = get_sites( array( 'fields' => 'ids' ) );
	foreach ( $pagelace_site_ids as $pagelace_site_id ) {
		switch_to_blog( $pagelace_site_id );
		pagelace_uninstall_site();
		restore_current_blog();
	}
} else {
	pagelace_uninstall_site();
}
