<?php
/**
 * Uninstall handler — removes all plugin data when the plugin is deleted
 * from the Plugins screen (not on plain deactivation).
 *
 * Removes the clw_embeddings table and plugin options. Embeddings are
 * derived data and can be regenerated by re-indexing after a reinstall,
 * so full cleanup is safe here.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

function clw_uninstall_site() {
	global $wpdb;

	delete_option( 'clw_gemini_api_key' );
	delete_option( 'clw_db_version' );

	$table = $wpdb->prefix . 'clw_embeddings';
	$wpdb->query( "DROP TABLE IF EXISTS `{$table}`" ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.SchemaChange
}

if ( is_multisite() ) {
	$clw_site_ids = get_sites( array( 'fields' => 'ids' ) );
	foreach ( $clw_site_ids as $clw_site_id ) {
		switch_to_blog( $clw_site_id );
		clw_uninstall_site();
		restore_current_blog();
	}
} else {
	clw_uninstall_site();
}
